### PR TITLE
fix: update NumNodes description

### PR DESCRIPTION
**Pull request by apeabody**

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
Hi, Andrew can you sign the CLA, please?

/ok-to-test
/lgtm

**Comment by apeabody** [comment]
> Hi, Andrew can you sign the CLA, please?
> 
> /ok-to-test /lgtm

Thanks, took some time to determine the correct Organization.  Cheers!

**Comment by upodroid** [comment]
The error isn't related to this change.

**Review by michelle192837 — APPROVED** [review]

**Pull request merged**
