### PR TITLE
allow kubetest2 gke accept major.minor cluster version

### PR DESCRIPTION
**Pull request by dprotaso**
Fixes: https://github.com/kubernetes-sigs/kubetest2/issues/130

### CODE REVIEW

**Review by MushuEE — COMMENTED** [review]
/lgtm

**Comment by dprotaso** [comment]
> kubetest2-gke/deployer/up_test.go:37:27: Using the variable on range scope `tc` in function literal (scopelint)

Hmmm.. these are false positives since we aren't spinning up goroutine or using `t.Parallel()`

Should I satisfy the linter or is there a `nolint` directive I should use

**Review by amwat — COMMENTED** [review]
/lgtm
/approve

Thank you!

**Comment by dprotaso** [comment]
@coryrc how does Knative pick up this change?

**Comment by coryrc** [comment]
> @coryrc how does Knative pick up this change?

I commented in our original thread: https://github.com/knative/serving/pull/11214

**Pull request merged**
