### PR TITLE
Removing EKS and bumping dependencies

### PR DESCRIPTION
**Pull request by chrislovecnm**
- removed kubetest2-eks
- cleaned up dependencies

Closes: https://github.com/kubernetes-sigs/kubetest2/issues/10

### CODE REVIEW

**Comment by amwat** [comment]
fixes: https://github.com/kubernetes-sigs/kubetest2/issues/10#issuecomment-667356549
FYI @gyuho 
Will definitely be happy to add it back whenever we sort out the dependencies. 

/lgtm
/approve

**Comment by gyuho** [comment]
Thanks @chrislovecnm @amwat

**Comment by BenTheElder** [comment]
Thanks @gyuho !

**Pull request merged**
